### DISCUSSION TITLE
IS this Compatitble with ib_async library?

### DISCUSSION THREAD

**Discussion by sadlrxn** [heshiming/ibga#13] [General]
https://github.com/ib-api-reloaded/ib_async

whenever i try to connect, it times out.

**Comment by heshiming** [comment]
If it times out while trying to connect, assuming you filled in hostname and port correctly, it then means IBGA is probably configured incorrectly, or failed to run. I can help if you provide your docker-compose.yml (make sure to remove the passwords), and perhaps a screenshot of the VNC.

**Reply by sadlrxn** [reply]
here is  my compose file. connecting on those ports is timing out. 

```yaml
ib-gateway:                                                                                                                                     
    restart: always                                                                                                                               
    networks:                                                                                                                                     
      - pnet                                                                                                                                      
    image: heshiming/ibga:latest                                                                                                                  
    environment:                                                                                                                                  
      - TERM=xterm                                                                                                                                
      - IB_USER=${IBGA_PAPER_USER}                                                                                                                
      - IB_PWD=${IBGA_PAPER_PWD}                                                                                                                  
      - IB_REGION=America                                                                                                                         
      - IB_TIMEZONE=America/New_York                                                                                                              
      - IB_LOGINTAB=IB API                                                                                                                        
      - IB_LOGINTYPE=Paper Trading                                                                                                                
      - IB_LOGOFF=11:55 PM                                                                                                                        
      - IB_APILOG=data                                                                                                                            
      - IB_LOGLEVEL=Error                                                                                                                         
      - IBGA_EXPORT_LOGS=true                                                                                                                     
      - IBGA_LOG_EXPORT_DIR=/home/ibg_logs                                                                                                        
    volumes:                                                                                                                                      
      - ./compose/ibga/program:/home/ibg                                                                                                          
      - ./compose/ibga/settings:/home/ibg_settings                                                                                                
      - ./compose/ibga/logs:/home/ibg_logs                                                                                                        
    ports:                                                                                                                                        
      - "5800:5800"                                                                                                                               
      - "4000:4000"                                                                                                                               
      - "4001:4001"                                                                                                                               
    healthcheck:
      test: curl -f localhost:5800
```
